// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh09bO_ktNneJSvCjm-7nZ6ZBd6cTWEf4',
    appId: '1:500030851669:web:344bb5f87750476c07a2dc',
    messagingSenderId: '500030851669',
    projectId: 'my-little-panda',
    authDomain: 'my-little-panda.firebaseapp.com',
    storageBucket: 'my-little-panda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtQIyE8Nqgf_Vsjl5SoA__kejKwXG3Vg8',
    appId: '1:500030851669:android:844cfe7314d9dc5007a2dc',
    messagingSenderId: '500030851669',
    projectId: 'my-little-panda',
    storageBucket: 'my-little-panda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJTLOiv7CvWV3kfmOW5x7UdtaSYdzPGgs',
    appId: '1:500030851669:ios:24d77ba9e46fb61b07a2dc',
    messagingSenderId: '500030851669',
    projectId: 'my-little-panda',
    storageBucket: 'my-little-panda.firebasestorage.app',
    iosBundleId: 'dev.flutterwing.framework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJTLOiv7CvWV3kfmOW5x7UdtaSYdzPGgs',
    appId: '1:500030851669:ios:24d77ba9e46fb61b07a2dc',
    messagingSenderId: '500030851669',
    projectId: 'my-little-panda',
    storageBucket: 'my-little-panda.firebasestorage.app',
    iosBundleId: 'dev.flutterwing.framework',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM7CqNjSHzvFRZU7mqAL-ysE3nPcsYpy0',
    appId: '1:500030851669:web:5baf7f0bb31dc2ba07a2dc',
    messagingSenderId: '500030851669',
    projectId: 'my-little-panda',
    authDomain: 'my-little-panda.firebaseapp.com',
    storageBucket: 'my-little-panda.firebasestorage.app',
  );
}
